### NumPy

NumPy (Numerical Python) é o pacote fundamental para computação científica com Python. Ele define
um novo tipo de contêiner - o ndarray (geralmente chamado apenas de array) - que suporta computação
rápida e eficiente. O NumPy também define as rotinas básicas para acessar e manipular esses arrays.

Arrays têm as seguintes propriedades (entre outras):

- Uma forma, que é uma tupla de inteiros. O número de inteiros é o número de dimensões na matriz e
os inteiros especificam o tamanho de cada dimensão.
- A dtype (data-type), que especifica o tipo dos objetos armazenados no array.
  

No NumPy, as dimensões de uma matriz são chamadas de eixos. Um exemplo de array com dtype int e
shape ((4, 5)) é mostrado abaixo. O primeiro eixo tem quatro elementos, cada um dos quais é uma matriz
unidimensional com 5 elementos.

[[ 0 1 2 3 4 ] [ 5 6 7 8 9 ] [ 10
11 12 13 14 ] [ 15 16 17 18
19 ]]

As principais diferenças entre arrays NumPy e listas Python são:

- Os objetos em uma matriz NumPy devem ser todos do mesmo tipo - booleanos, inteiros, floats, números complexos ou strings.
- • O tamanho de uma matriz é fixado na criação e não pode ser alterado posteriormente.
- Os arrays podem ser multidimensionais.
- Operações matemáticas podem ser aplicadas diretamente a arrays. Quando isso é feito, eles são
aplicados elemento a elemento ao array, gerando outro array como saída. Isso é muito mais rápido
do que iterar em uma lista.
- A indexação para arrays é mais poderosa do que para listas e inclui a indexação usando arrays
inteiros e booleanos.
- Fatiar um array produz uma visualização do array original, não uma cópia. Modificando isso view mudará o array original.

####  Criação de Array

Array NumPy podem ser criadas: 

- De uma lista. Os elementos da lista precisam ser todos do mesmo tipo ou de um tipo que possa ser convertido
para o mesmo tipo. Por exemplo, uma lista que consiste em inteiros e flutuantes gerará uma matriz de flutuantes,
pois os inteiros podem ser convertidos em flutuantes.
- De acordo com uma determinada forma. A matriz será inicializada de forma diferente, dependendo do função usada.
- De outra matriz. A nova matriz terá o mesmo formato da matriz existente, e pode ser uma cópia ou inicializado com alguns outros valores.
- Como resultado de uma operação em outros arrays. Os operadores matemáticos padrão podem ser aplicados
diretamente a arrays. O resultado é um array da mesma forma onde a operação foi realizada separadamente
nos elementos correspondentes.

As funções a seguir são as principais:

|func|Des|
|---|---|
|-|Crie uma matriz a partir de uma lista.|
|-|Retorna uma matriz de números espaçados uniformemente em um intervalo especificado|
|-|Retorna uma matriz de inteiros espaçados uniformemente dentro de um determinado intervalo|
|-|Retorna um novo array de uma determinada forma e tipo, sem inicializar as entradas.|
|-|Retorna um novo array de uma determinada forma e tipo, preenchido com zeros.|
|-|Retorna um novo array de uma determinada forma e tipo, preenchido com uns.|
|-|Retorna uma nova matriz com a mesma forma e tipo de uma determinada matriz.|
|-|Retorna uma matriz de zeros com a mesma forma e tipo de uma determinada matriz.|
|-|Retorne uma matriz de uns com a mesma forma e tipo de uma determinada matriz.|
|-|Retorna uma cópia de array do objeto fornecido.|
|-|Retorna um par de matrizes de grade 2D x e y de matrizes de coordenadas 1D x e y.|

Estas funções são ilustradas abaixo. O alias "np" é uma prática padrão ao usar o NumPy.

In [1]:
# array(object) cria um array a partir de uma lista - 
# observe que os arrays são impressos sem vírgulas.

import numpy as np

x=np.array([1,2,3])
print(x)

[1 2 3]


In [2]:
# array(object, dtype) cria um array do tipo dtype - 
# os inteiros agora são convertidos em floats.

x = np.array([1, 2, 3], dtype=float)
print(x)

[1. 2. 3.]


In [3]:
# linspace(start, stop, num) retorna num pontos igualmente espaçados, incluindo pontos finais.

x = np.linspace(0, 1, 6)
print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


In [4]:
# arange retorna uma matriz de valores uniformemente espaçados dentro de um determinado intervalo.

x = np.arange(5)
print(x)

[0 1 2 3 4]


As funções vazias, zeros e uns pegam um argumento de forma e criam uma matriz dessa
forma, inicializada conforme apropriado.

In [5]:
# empty(shape) retorna um array de shape shape, inicialmente preenchido com lixo.
 
x = np.empty((3, 2))
print(x)

[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]


In [6]:
# zeros(shape) retorna um array de shape shape preenchido com zeros - 
# observe que o tipo padrão é float.

x = np.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# ones(shape, dtype) retorna um array de shape shape preenchido com uns - 
# usando dtype=int converte os elementos para o tipo int.

x = np.ones((2, 3), dtype=int)
print(x)

[[1 1 1]
 [1 1 1]]


Arrays podem ser criados diretamente de outros arrays usando like vazio, like zero, like
uns e copy.

In [8]:
# Crie um array de floats usando arange.

x = np.arange(3, dtype=float)
print(x)

[0. 1. 2.]


In [9]:
# y tem a mesma forma que x, mas inicialmente está cheio de lixo.

y = np.empty_like(x)
print(y)

[0. 1. 2.]


In [10]:
# y tem a mesma forma que x, mas é inicializado com zeros.

y = np.zeros_like(x)
print(y)

[0. 0. 0.]


In [11]:
# y tem a mesma forma que x, mas é inicializado com uns.

y = np.ones_like(x)
print(y)

[1. 1. 1.]


In [12]:
# y é uma cópia de x - mudar y não mudará x.

y = np.copy(x)
print(y)

[0. 1. 2.]


A função meshgrid(x, y) cria arrays bidimensionais a partir de eixos de coordenadas xey
unidimensionais. Uma matriz contém as coordenadas x de todos os pontos no plano xy definidos por
esses eixos e a outra contém as coordenadas y. Um exemplo é mostrado abaixo.

In [13]:
# meshgrid cria matrizes de coordenadas 2D x e y a partir de matrizes de coordenadas 1D x e y.

x = np.arange(4)
y = np.arange(3)
X, Y = np.meshgrid(x, y)

In [14]:
# X é uma matriz 2D contendo apenas as coordenadas x de pontos no plano xy.

print(X)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [15]:
# Y é uma matriz 2D contendo apenas as coordenadas y de pontos no plano xy.

print(Y)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]


A função meshgrid é frequentemente usada quando queremos aplicar uma função de duas variáveis
a pontos no plano xy. O exemplo a seguir usa as matrizes X e Y acima.

In [ ]:
# A função distância encontra a distância de um ponto (x, y) da origem, 
# arredondada para 3 casas decimais pela função around .

from math import sqrt

def distance(x, y):
    return np.round(sqrt(x**2 + y**2), 3)

print(distance(X, Y))

#### Propriedades de Arrays

As propriedades de uma matriz podem ser acessadas da seguinte maneira.

In [17]:
# x é do tipo numpy.ndarray.
import numpy as np

x = np.arange(6)
type(x)

numpy.ndarray

In [18]:
# dtype retorna o tipo de elemento - um inteiro de 64 bits.

x.dtype

dtype('int32')

In [19]:
# x é uma matriz unidimensional com 6 elementos no primeiro eixo.

x.shape

(6,)

É possível criar um array a partir dos elementos de um array existente, mas com as propriedades
alteradas.

- O número de dimensões e o tamanho de cada dimensão podem ser alterados usando reshape
(desde que o número total de elementos permaneça inalterado).
- O dtype pode ser alterado usando astype.

In [20]:
# reshape cria uma exibição de uma matriz com o mesmo número de elementos, mas com uma forma diferente.

x = np.arange(6).reshape((2, 3))
print(x)

[[0 1 2]
 [3 4 5]]


In [21]:
# astype converte os inteiros em x em floats em y. 
# Isso cria um novo array - modificá-lo não alterará o original.

y = x.astype(float)
print(y)

[[0. 1. 2.]
 [3. 4. 5.]]


#### Operações de Arrays

A aritmética de matriz é feita elemento por elemento. As operações são aplicadas a cada
elemento de um array, com cada resultado tornando-se um elemento em um novo array.

In [22]:
# Crie um array de inteiros consecutivos usando arange.

import numpy as np

x = np.arange(4)
print(x)

[0 1 2 3]


In [23]:
# 1 é adicionado a cada elemento do array x.

print(x +1)

[1 2 3 4]


In [24]:
# Cada elemento do array x é multiplicado por 2.

print(x *2)

[0 2 4 6]


In [25]:
# Cada elemento do array x é elevado ao quadrado.

print(x ** 2)

[0 1 4 9]


In [26]:
# Crie um segundo array

# y = array([3, 2, 5, 1])

In [ ]:
# Os elementos de x são adicionados aos elementos correspondentes de y elemento por elemento.

print(x)
print(y)
print(x + y)

In [ ]:
# A exponenciação é feita usando elementos correspondentes dos arrays x e y.

print( x**y )

Os operadores de comparação e outras expressões booleanas também são aplicados elemento
por elemento. A expressão booleana é aplicada a cada elemento da matriz, com cada resultado
tornando-se um elemento em uma nova matriz booleana.

In [29]:
# A expressão booleana é avaliada para cada elemento separadamente, resultando em um array de booleanos.

x = np.arange(5)

print(x)
print(x % 2 == 0)

[0 1 2 3 4]
[ True False  True False  True]


In [30]:
# A comparação é feita elemento a elemento entre os elementos dos arrays x e y. O resultado é uma matriz de booleanos.

x = np.arange(4)
y = np.array([3, 2, 5, 1])

print(x)
print(y)

print(x < y)

[0 1 2 3]
[3 2 5 1]
[ True  True  True False]


O NumPy contém versões vetorizadas de todas as funções matemáticas básicas. Observe que
eles precisam ser importados antes de podermos usá-los. Alguns exemplos são dados a seguir.

In [31]:
# Crie um array.

x = np.arange(3)
print(x)

[0 1 2]


In [32]:
# sin é aplicado a cada elemento, para criar uma nova matriz.

print(np.sin(x))

[0.         0.84147098 0.90929743]


In [33]:
# exp é a ópera exponencial tor

print(np.exp(x))

[1.         2.71828183 7.3890561 ]


In [34]:
# random.randint retorna uma matriz de um determinado tamanho preenchida com inteiros selecionados aleatoriamente de um determinado intervalo.

x = np.random.randint(5, size=(2, 3))
print(x)

[[1 0 3]
 [1 1 2]]


In [35]:
# min e max calculam os valores mínimo e máximo em todo o array.

print(x.min(), x.max())

0 3


In [36]:
# O argumento do eixo localiza cada mínimo ao longo de um determinado eixo. 
# A matriz resultante tem a forma da matriz original, mas com o eixo especificado removido.

print(x.min(axis= 0))
print(x.min(axis= 1))

[1 0 2]
[0 1]


In [37]:
# soma soma todos os elementos de uma matriz.

print(x.sum())

8


In [38]:
# Fornecer as somas dos argumentos do eixo ao longo do eixo especificado.

print(x.sum(axis= 0))

[2 1 5]


#### Indexação e divisão de Arrays

As matrizes podem ser indexadas e divididas usando colchetes da mesma forma que as listas.

- Um índice ou filtro start:stop:step precisa ser fornecido para cada eixo, separado por virgulas
- A indexação é baseada em zero, assim como nas listas.
- Fatiar um array produz uma visualização do array original, não uma cópia. Modificando isso view mudará o array original.

In [39]:
# reshape fornece uma maneira rápida de criar uma matriz 2D a partir de uma matriz 1D.

import numpy as np

x = np.arange(20).reshape((4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [40]:
# A indexação é feita em cada eixo em ordem - linha 1, coluna 2.

print(x[1,2])

7


In [41]:
# A linha 1 pode ser selecionada usando um número inteiro.

print(x[1])

[5 6 7 8 9]


In [42]:
# O fatiamento pode ser usado para selecionar o primeiro elemento de cada eixo (ou seja, coluna 1).

print(x[:,1])

[ 1  6 11 16]


In [43]:
# Divida as linhas 1 e 2 usando 1:3, depois divida as colunas 1, 2 e 3 usando 1:4.

print(x[1:3, 1:4])

[[ 6  7  8]
 [11 12 13]]


#### Indexação com Arrays Inteiros

Embora o fatiamento possa ser usado para retornar um subconjunto de elementos de uma matriz, seu
uso é restrito à seleção de elementos consecutivos ou à seleção de elementos separados pelo mesmo
valor fixo. Às vezes, queremos selecionar algum subconjunto arbitrário de uma matriz, possivelmente
até mesmo selecionando o mesmo elemento mais de uma vez. A indexação de matriz inteira fornece
uma maneira de fazer isso.

- O índice é um array NumPy de números inteiros.
- Cada inteiro na matriz de índice seleciona um elemento correspondente da matriz de destino.
- O resultado é uma matriz em que os primeiros eixos têm a mesma forma da matriz de índice.

fazer indexãoas

In [44]:
# Primeiro crie o array usando arange, depois eleve ao quadrado cada elemento

import numpy as np

x = np.arange(9)**2
print(x)

[ 0  1  4  9 16 25 36 49 64]


In [45]:
# Um array é retornado contendo elementos do primeiro array, 
# selecionados de acordo com os inteiros do segundo array.

index = np.array([2, 5])
print(x[index])

[ 4 25]


O índice pode ser uma matriz inteira de qualquer forma e pode incluir duplicatas, conforme mostrado
abaixo.

In [46]:
# A matriz de indexação contém em números que são usados para indexar na matriz de destino.
# Observe que os mesmos elementos (2, neste caso) podem ser selecionados mais de uma vez.

index = np.array([[2, 3], [7, 2]])
print(index)

[[2 3]
 [7 2]]


In [47]:
# Ao indexar um array unidimensional usando um array inteiro, o array retornado tem o mesmo formato do array de indexação.

print(x[index])

[[ 4  9]
 [49  4]]


A matriz de destino também pode ser uma matriz multidimensional. Nesse caso, os elementos
selecionados pelo array de índice serão os elementos do array do alvo.

In [48]:
# A matriz de cores é uma matriz bidimensional, portanto, os elementos das cores são um matrizes dimensionais (as linhas). 



colors = np.array([[1., 0., 0.],
                   [0., 1., 0.],
                   [0., 0., 1.]])

index = np.array([1, 0, 2, 1, 1, 0])

print(colors[index])

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


A matriz de cores pode ser considerada como uma “tabela de pesquisa” - a indexação de inteiros procura os elementos dessa tabela e usa os valores encontrados para construir o resultado.

#### Indexação com Arrays booleanas

Também podemos indexar usando matrizes de booleanos. Nesse caso, a matriz de indexação age como
uma máscara, deixando passar apenas os elementos na matriz de destino que correspondem aos
valores True na matriz de indexação.

In [49]:
# Somente os elementos com um correspondente a True na máscara print(x[mask]) são selecionados.

import numpy as np

x = np.arange(4)
mask = np.array([True, True, False, True])

print(x)
print(x[mask])

[0 1 2 3]
[0 1 3]


Um uso comum dessa técnica é selecionar os elementos de uma matriz que satisfaçam alguma
condição. Isso pode ser feito primeiro aplicando a condição à matriz para gerar uma matriz de booleanos
e, em seguida, usando a matriz resultante como um índice. O resultado é que apenas os elementos
para os quais a condição é verdadeira são selecionados.

In [50]:
# index3 e index5 são arrays booleanos contendo elementos True para os inteiros que são divisíveis por 3 e 5, respectivamente.

x = np.arange(20)

index3 = (x % 3 == 0)
index5 = (x % 5 == 0)

In [51]:
# Selecione apenas os elementos de x que são divisíveis por 3.

print(x[index3])

[ 0  3  6  9 12 15 18]


In [52]:
# Selecione apenas os elementos de x que são divisíveis por 5.

print(x[index5])

[ 0  5 10 15]


In [53]:
# A função lógica ou executa um ”ou” elementar. O resultado são os inteiros divisíveis por 3 ou 5.

print(x[np.logical_or(index3, index5)])

[ 0  3  5  6  9 10 12 15 18]


In [54]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0



### End.