### Array Creation

In [1]:
# array(object) creates an array from a list - 
# note that arrays are printed without commas.
import numpy as np

x=np.array([1,2,3])
print(x)

[1 2 3]


In [2]:
# array(object, dtype) creates an array of type dtype - 
# the integers are now cast to floats.

x = np.array([1, 2, 3], dtype=float)
print(x)

[1. 2. 3.]


In [3]:
# linspace(start, stop, num) returns num equally spaced points, including endpoints.

x = np.linspace(0, 1, 6)
print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


In [4]:
# arange returns an array of evenly spaced values within a given interval.

x = np.arange(5)
print(x)

[0 1 2 3 4]


The functions empty, zeros and ones all take a shape argument and create an array of
that shape, initialized as appropriate.

In [5]:
# empty(shape) returns an array of shape shape, 
# initially filled with garbage.
 
x = np.empty((3, 2))
print(x)

[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]


In [6]:
# zeros(shape) returns an array of shape shape filled with zeros - 
# note the default type is float.

x = np.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# ones(shape, dtype) returns an array of shape shape filled with
# ones - using dtype=int casts the elements to type int.

x = np.ones((2, 3), dtype=int)
print(x)

[[1 1 1]
 [1 1 1]]


Arrays can be created directly from other arrays using empty like, zeros like, ones like
and copy.

In [8]:
# Create an array of floats using arange.

x = np.arange(3, dtype=float)
print(x)

[0. 1. 2.]


In [9]:
# y has the same shape as x, but is initially filled with garbage.

y = np.empty_like(x)
print(y)

[0. 1. 2.]


In [10]:
# y has the same shape as x, but is initialized with zeros.

y = np.zeros_like(x)
print(y)

[0. 0. 0.]


In [11]:
# y has the same shape as x, but is initialized with ones.

y = np.ones_like(x)
print(y)

[1. 1. 1.]


In [12]:
# y is a copy of x - changing y will not change x.

y = np.copy(x)
print(y)

[0. 1. 2.]


In [13]:
# meshgrid creates 2D x- and
# y- coordinate arrays from 1D
# x- and y- coordinate arrays.

x = np.arange(4)
y = np.arange(3)
X, Y = np.meshgrid(x, y)

In [14]:
# X is a 2D array containing just the x-coordinates of points in the xy plane.

print(X)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [15]:
# Y is a 2D array containing just the y-coordinates of points in the xy plane.

print(Y)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]


In [ ]:
# The function distance finds the distance of a point (x, y)
# from the origin, rounded to 3 decimal places by the around function.
from math import sqrt

def distance(x, y):
    return np.round(sqrt(x**2 + y**2), 3)

print(distance(X, Y))

### Array Properties

In [17]:
# x is of type numpy number
import numpy as np

x = np.arange(6)
type(x)

numpy.ndarray

In [18]:
# dtype return the element type a 32-bit integer

x.dtype

dtype('int32')

In [19]:
# x is a 1-dimensional array with 6 elements in the first axis

x.shape

(6,)

In [20]:
# reshape creates a view of an array with the same number of elements, but a different shape.

x = np.arange(6).reshape((2, 3))
print(x)

[[0 1 2]
 [3 4 5]]


In [21]:
# astype casts the integers in x to floats in y. This creates a
# new array - modifying it will not alter the original.

y = x.astype(float)
print(y)

[[0. 1. 2.]
 [3. 4. 5.]]


### Array Operations

In [22]:
# Create an array of consecutive integers using arange.

import numpy as np

x = np.arange(4)
print(x)

[0 1 2 3]


In [23]:
# 1 is added to every element of the array x

print(x +1)

[1 2 3 4]


In [24]:
# Every element of the array x is mutiplied by 2

print(x *2)

[0 2 4 6]


In [25]:
# Every element of the array x is squared

print(x ** 2)

[0 1 4 9]


In [26]:
# create a second array

# y = array([3, 2, 5, 1])

In [ ]:
# The elements of x are added to the corresponding elements 
# of y on an element-by-element basis.

print(x)
print(y)
print(x + y)

In [ ]:
# Exponentiation is done using corresponding elements of the arrays x and y.

print( x**y )

In [29]:
# The Boolean expression is evaluated for each element
# separately, resulting in an array of booleans

x = np.arange(5)
print(x)
print(x % 2 == 0)

[0 1 2 3 4]
[ True False  True False  True]


In [30]:
# The comparison is done on an elementwise basis between elements 
# of arrays x amd y. The result is an array of booleans.

x = np.arange(4)
y = np.array([3, 2, 5, 1])
print(x)
print(y)
print(x < y)

[0 1 2 3]
[3 2 5 1]
[ True  True  True False]


In [31]:
# Create an array

x = np.arange(3)
print(x)

[0 1 2]


In [32]:
# sin is applied to each element to create a new array

print(np.sin(x))

[0.         0.84147098 0.90929743]


In [33]:
# exp is the exponetial operator

print(np.exp(x))

[1.         2.71828183 7.3890561 ]


In [34]:
# random.randint return an array of a given size filled with randomly selected intergers form a given range.count

x = np.random.randint(5, size=(2, 3))
print(x)

[[4 0 3]
 [2 1 4]]


In [35]:
# min and max calculate the minimum and maximum values across the entire array

print(x.min(), x.max())

0 4


In [36]:
# The axis argument finds each minimum along a given axis.
# The resulting array is the shape of the original array, but with the given axis removed.

print(x.min(axis= 0))
print(x.min(axis= 1))

[2 0 3]
[0 1]


In [37]:
# sum sums all the elements of an array

print(x.sum())

14


In [38]:
# Providing the axis argument sums along the given axis.

print(x.sum(axis= 0))

[6 1 7]


### Array Indexing and Slicing

In [39]:
# reshape provides a fast way to create a 2D array from a 1D array.

import numpy as np
x = np.arange(20).reshape((4, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [40]:
# Indexing is done into each axis in order - row 1, column 2.

print(x[1,2])

7


In [41]:
# Row 1 can be selected using an integer.

print(x[1])

[5 6 7 8 9]


In [42]:
# Slicing can be used to select the first element of every axis (i.e. column 1).

print(x[:,1])

[ 1  6 11 16]


In [43]:
# Slice rows 1 and 2 using 1:3, then slice columns 1, 2 and 3 using 1:4.

print(x[1:3, 1:4])

[[ 6  7  8]
 [11 12 13]]


### Indexing with Integer Arrays

In [44]:
# First create the array using arange, 
# then square each element.

import numpy as np
x = np.arange(9)**2
print(x)

[ 0  1  4  9 16 25 36 49 64]


In [45]:
# An array is returned containing elements from the first array,
# selected according to the integers in the second array.

index = np.array([2, 5])
print(x[index])

[ 4 25]


In [46]:
# The indexing array contains integers that are used to index
# into the target array. Note that the same elements (2, in this case) 
# can be selected more than once.

index = np.array([[2, 3], [7, 2]])
print(index)

[[2 3]
 [7 2]]


In [47]:
# When indexing a one-dimensional array using an integer array, 
# the returned array has the same shape as the indexing array.

print(x[index])

[[ 4  9]
 [49  4]]


In [48]:
# The colors array is a two-dimensional array, so the
# elements of colors are one-dimensional arrays (the rows).

colors = np.array([[1., 0., 0.],
                   [0., 1., 0.],
                   [0., 0., 1.]])

index = np.array([1, 0, 2, 1, 1, 0])

print(colors[index])

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


dimensional arrays (the rows). The colors array can be thought of as a "lookup table" - integer indexing looks up the elements of this table, and uses the values found to construct the result.

### Indexing with Boolean Arrays

In [49]:
# Only the elements with a matching True in the mask are selected.

import numpy as np

x = np.arange(4)
mask = np.array([True, True, False, True])

print(x)
print(x[mask])

[0 1 2 3]
[0 1 3]


In [50]:
# index3 and index5 are boolean arrays containing
# True elements for the integers that are divisible 
# by 3 and 5 respectively.

x = np.arange(20)
index3 = (x % 3 == 0)
index5 = (x % 5 == 0)

In [51]:
# Select just the elements of x that are divisible by 3.

print(x[index3])

[ 0  3  6  9 12 15 18]


In [52]:
# Select just the elements of x that are divisible by 5.

print(x[index5])

[ 0  5 10 15]


In [53]:
# The function logical or performs an elementwise "or".
# The result is the integers divisible by either 3 or 5.

print(x[np.logical_or(index3, index5)])

[ 0  3  5  6  9 10 12 15 18]


In [54]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

numpy: 1.23.0
sys  : 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]



### End.