### Array Creation

- array - Create an array from a list.
---
- linspace - Return an array of evenly spaced numbers over a specified interval.
---
- arange - Return an array of evenly spaced integers within a given interval.
---
- empty - Return an a new array of a given shape and type, without initializing entries.
---
- zeros - Return an a new array of a given shape and type, filled with zeros.
---
- ones - Return an a new array of a given shape and type, filled with ones.
---
- empty_like - Return a new array with the same shape and type as a given array.
---
- zeros_like - Return an array of zeros with the same shape and type as a given array.
---
- ones_like - Return an array of ones with the same shape and type as a given array.
---
- copy - Return an array copy of the given object.
---
- meshgrid - Returns a pair of 2D x and y grid arrays from 1D x and y coordinate arrays.

In [16]:
# array(object) creates an array from a list - 
# note that arrays are printed without commas.
import numpy as np

x=np.array([1,2,3])
print(x)

[1 2 3]


In [17]:
# array(object, dtype) creates an array of type dtype - 
# the integers are now cast to floats.

x = np.array([1, 2, 3], dtype=float)
print(x)

[1. 2. 3.]


In [18]:
# linspace(start, stop, num) returns num equally spaced points, including endpoints.

x = np.linspace(0, 1, 6)
print(x)

[0.  0.2 0.4 0.6 0.8 1. ]


In [19]:
# arange returns an array of evenly spaced values within a given interval.

x = np.arange(5)
print(x)

[0 1 2 3 4]


The functions empty, zeros and ones all take a shape argument and create an array of
that shape, initialized as appropriate.

In [20]:
# empty(shape) returns an array of shape shape, 
# initially filled with garbage.
 
x = np.empty((3, 2))
print(x)

[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]


In [21]:
# zeros(shape) returns an array of shape shape filled with zeros - 
# note the default type is float.

x = np.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
# ones(shape, dtype) returns an array of shape shape filled with
# ones - using dtype=int casts the elements to type int.

x = np.ones((2, 3), dtype=int)
print(x)

[[1 1 1]
 [1 1 1]]


Arrays can be created directly from other arrays using empty like, zeros like, ones like
and copy.

In [23]:
# Create an array of floats using arange.

x = np.arange(3, dtype=float)
print(x)

[0. 1. 2.]


In [24]:
# y has the same shape as x, but is initially filled with garbage.

y = np.empty_like(x)
print(y)

[0. 1. 2.]


In [25]:
# y has the same shape as x, but is initialized with zeros.

y = np.zeros_like(x)
print(y)

[0. 0. 0.]


In [26]:
# y has the same shape as x, but is initialized with ones.

y = np.ones_like(x)
print(y)

[1. 1. 1.]


In [27]:
# y is a copy of x - changing y will not change x.

y = np.copy(x)
print(y)

[0. 1. 2.]


In [28]:
# meshgrid creates 2D x- and
# y- coordinate arrays from 1D
# x- and y- coordinate arrays.

x = np.arange(4)
y = np.arange(3)
X, Y = np.meshgrid(x, y)

In [29]:
# X is a 2D array containing just the x-coordinates of points in the xy plane.

print(X)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [30]:
# Y is a 2D array containing just the y-coordinates of points in the xy plane.

print(Y)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]


In [ ]:
# The function distance finds the distance of a point (x, y)
# from the origin, rounded to 3 decimal places by the around function.
from math import sqrt

def distance(x, y):
    return np.round(sqrt(x**2 + y**2), 3)

print(distance(X, Y))

### Array Properties

In [34]:
# x is of type numpy number
import numpy as np

x = np.arange(6)
type(x)

numpy.ndarray

In [35]:
# dtype return the element type a 32-bit integer

x.dtype

dtype('int32')

In [36]:
# x is a 1-dimensional array with 6 elements in the first axis

x.shape

(6,)

In [37]:
# reshape creates a view of an array with the same number of elements, but a different shape.

x = np.arange(6).reshape((2, 3))
print(x)

[[0 1 2]
 [3 4 5]]


In [38]:
# astype casts the integers in x to floats in y. This creates a
# new array - modifying it will not alter the original.

y = x.astype(float)
print(y)

[[0. 1. 2.]
 [3. 4. 5.]]


### Array Operations

In [39]:
# Create an array of consecutive integers using arange.

import numpy as np

x = np.arange(4)
print(x)

[0 1 2 3]


In [40]:
# 1 is added to every element of the array x

print(x +1)

[1 2 3 4]


In [41]:
# Every element of the array x is mutiplied by 2

print(x *2)

[0 2 4 6]


In [42]:
# Every element of the array x is squared

print(x ** 2)

[0 1 4 9]


In [43]:
# create a second array

# y = array([3, 2, 5, 1])

In [ ]:
# The elements of x are added to the corresponding elements 
# of y on an element-by-element basis.

print(x)
print(y)
print(x + y)

In [ ]:
# Exponentiation is done using corresponding elements of the arrays x and y.

print( x**y )

In [ ]:
# The Boolean expression is evaluated for each element
# separately, resulting in an array of booleans

x = np.arange(5)
print(x)
print(x % 2 == 0)

In [ ]:
# The comparison is done on an elementwise basis between elements 
# of arrays x amd y. The result is an array of booleans.

x = np.arange(4)
y = np.array([3, 2, 5, 1])
print(x)
print(y)
print(x < y)

In [ ]:
# Create an array

x = np.arange(3)
print(x)

In [ ]:
# sin is applied to each element to create a new array

print(np.sin(x))

In [ ]:
# exp is the exponetial operator

print(np.exp(x))

In [ ]:
# random.randint return an array of a given size filled with randomly selected intergers form a given range.count

x = np.random.randint(5, size=(2, 3))
print(x)

In [ ]:
# min and max calculate the minimum and maximum values across the entire array

print(x.min(), x.max())

In [ ]:
# The axis argument finds each minimum along a given axis.
# The resulting array is the shape of the original array, but with the given axis removed.

print(x.min(axis= 0))
print(x.min(axis= 1))

In [ ]:
# sum sums all the elements of an array

print(x.sum())

In [ ]:
# Providing the axis argument sums along the given axis.

print(x.sum(axis= 0))

### Array Indexing and Slicing

In [ ]:
reshape provides a fast way to
create a 2D array from a 1D
array.

import numpy as np
x = np.arange(20).reshape((4, 5))
print(x)

In [ ]:
Indexing is done into each axis
in order - row 1, column 2.

print(x[1,2])

In [ ]:
Row 1 can be selected using an
integer.

print(x[1])

In [ ]:
Slicing can be used to select
the first element of every axis
(i.e. column 1).

print(x[:,1])

In [ ]:
# Slice rows 1 and 2 using 1:3, then slice columns 1, 2 and 3 using 1:4.

print(x[1:3, 1:4])

### Indexing with Integer Arrays

In [ ]:
<code>

### Indexing with Boolean Arrays

In [ ]:
<code>

### End.